# Generated by Django 5.2.3 on 2025-07-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='specialization',
            field=models.CharField(max_length=90),
        ),
    ]
